
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricar
 */
public class Caixas extends javax.swing.JFrame {
    List<Senha> listaSenhas;
    int numero;
    String tipo;
    /**
     * Creates new form Caixas
     */
    public Caixas() {
        initComponents();
        numero = 0;
        listaSenhas = new ArrayList<Senha>();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SenhaComum = new javax.swing.JButton();
        SenhaRapido = new javax.swing.JButton();
        SenhaPriori = new javax.swing.JButton();
        senhacliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Caixa1 = new javax.swing.JButton();
        Caixa2 = new javax.swing.JButton();
        Caixa3 = new javax.swing.JButton();
        Caixa4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        painelsenha = new javax.swing.JLabel();
        painelcaixa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("ESCOLHA O SEU TIPO DE ATENDIMENTO:");

        SenhaComum.setText("COMUM");
        SenhaComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaComumActionPerformed(evt);
            }
        });

        SenhaRapido.setText("RÁPIDO");
        SenhaRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaRapidoActionPerformed(evt);
            }
        });

        SenhaPriori.setText("PRIORITÁRIO");
        SenhaPriori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaPrioriActionPerformed(evt);
            }
        });

        senhacliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        senhacliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaclienteActionPerformed(evt);
            }
        });

        jLabel3.setText("SUA SENHA É:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(SenhaComum)
                                        .addGap(28, 28, 28)))
                                .addGap(18, 18, 18)
                                .addComponent(SenhaRapido)))
                        .addGap(38, 38, 38)
                        .addComponent(SenhaPriori)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaComum)
                    .addComponent(SenhaRapido)
                    .addComponent(SenhaPriori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PARA CLIENTES:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Caixa1.setText("CAIXA 1");
        Caixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa1ActionPerformed(evt);
            }
        });

        Caixa2.setText("CAIXA 2");
        Caixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa2ActionPerformed(evt);
            }
        });

        Caixa3.setText("CAIXA 3");
        Caixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa3ActionPerformed(evt);
            }
        });

        Caixa4.setText("CAIXA 4");
        Caixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Caixa3)
                    .addComponent(Caixa1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Caixa2)
                    .addComponent(Caixa4))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caixa1)
                    .addComponent(Caixa2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caixa3)
                    .addComponent(Caixa4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("PARA CAIXAS:");

        painelsenha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        painelsenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        painelsenha.setText("-");

        painelcaixa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        painelcaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        painelcaixa.setText("-");
        painelcaixa.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelcaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(painelsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelcaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SenhaComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaComumActionPerformed
        numero++;
        Senha comum = new Senha("C", numero);
        listaSenhas.add(comum);
        senhacliente.setText(String.valueOf(comum.getTipo())+"-"+ String.valueOf(comum.getNumero()));
        
        
        
    }//GEN-LAST:event_SenhaComumActionPerformed

    private void Caixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa1ActionPerformed
      boolean chamasenha = false;
        
         Iterator<Senha> itr = listaSenhas.iterator();
          
          while(itr.hasNext()){
          Senha s = itr.next();
          if(s.getTipo().equals("P")){
          itr.remove();
          painelsenha.setText(s.getTipo()+ "-" + s.getNumero());
          painelcaixa.setText(" CAIXA " + "-" + " 1 " );
          chamasenha = true;
          break;
        }
            } if (chamasenha == false){
              Iterator<Senha> itr2 =  listaSenhas.iterator();
                    while(itr2.hasNext()){
                    Senha s2 = itr2.next();
                    listaSenhas.get(0);
                    itr2.remove();
                    painelsenha.setText(s2.getTipo()+ "-" + s2.getNumero());
                    painelcaixa.setText(" CAIXA " + "-" + " 1 " );
                    break;
                }
            }          
                
       
            
      
    
    }//GEN-LAST:event_Caixa1ActionPerformed

    private void SenhaRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaRapidoActionPerformed
        numero++;
        Senha rapido = new Senha("R", numero);
        listaSenhas.add(rapido);
        senhacliente.setText(String.valueOf(rapido.getTipo())+ "-"+ String.valueOf(rapido.getNumero()));
    }//GEN-LAST:event_SenhaRapidoActionPerformed

    private void SenhaPrioriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaPrioriActionPerformed
        numero++;
        Senha prioritaria = new Senha("P", numero);
        listaSenhas.add(prioritaria);
        senhacliente.setText(String.valueOf(prioritaria.getTipo())+ "-" + String.valueOf(prioritaria.getNumero()));
    }//GEN-LAST:event_SenhaPrioriActionPerformed

    private void senhaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaclienteActionPerformed

    private void Caixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa2ActionPerformed
         boolean chamasenha = false;
        
         Iterator<Senha> itr = listaSenhas.iterator();
          
          while(itr.hasNext()){
          Senha s = itr.next();
          if(s.getTipo().equals("R")){
          itr.remove();
          painelsenha.setText(s.getTipo()+ "-" + s.getNumero());
          painelcaixa.setText(" CAIXA " + "-" + " 1 " );
          chamasenha = true;
          break;
        }
            } if (chamasenha == false){
              Iterator<Senha> itr2 =  listaSenhas.iterator();
                    while(itr2.hasNext()){
                    Senha s2 = itr2.next();
                    listaSenhas.get(0);
                    itr2.remove();
                    painelsenha.setText(s2.getTipo()+ "-" + s2.getNumero());
                    painelcaixa.setText(" CAIXA " + "-" + " 2 " );
                    break;
                }
            }          
    }//GEN-LAST:event_Caixa2ActionPerformed

    private void Caixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa3ActionPerformed

       boolean chamasenha = false;
        
         Iterator<Senha> itr = listaSenhas.iterator();
          
          while(itr.hasNext()){
          Senha s = itr.next();
          if(s.getTipo().equals("R")){
          itr.remove();
          painelsenha.setText(s.getTipo()+ "-" + s.getNumero());
          painelcaixa.setText(" CAIXA " + "-" + " 3 " );
          chamasenha = true;
          break;
        }
            } if (chamasenha == false){
              Iterator<Senha> itr2 =  listaSenhas.iterator();
                    while(itr2.hasNext()){
                    Senha s2 = itr2.next();
                    listaSenhas.get(0);
                    itr2.remove();
                    painelsenha.setText(s2.getTipo()+ "-" + s2.getNumero());
                    painelcaixa.setText(" CAIXA " + "-" + " 1 " );
                    break;
                }
            }          
    }//GEN-LAST:event_Caixa3ActionPerformed

    private void Caixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa4ActionPerformed
         boolean chamasenha = false;
        
         Iterator<Senha> itr = listaSenhas.iterator();
          
          while(itr.hasNext()){
          Senha s = itr.next();
          if(s.getTipo().equals("C")){
          itr.remove();
          painelsenha.setText(s.getTipo()+ "-" + s.getNumero());
          painelcaixa.setText(" CAIXA " + "-" + " 1 " );
          chamasenha = true;
          break;
        }
            } if (chamasenha == false){
              Iterator<Senha> itr2 =  listaSenhas.iterator();
                    while(itr2.hasNext()){
                    Senha s2 = itr2.next();
                    listaSenhas.get(0);
                    itr2.remove();
                    painelsenha.setText(s2.getTipo()+ "-" + s2.getNumero());
                    painelcaixa.setText(" CAIXA " + "-" + " 1 " );
                    break;
                }
            }          
        
    }//GEN-LAST:event_Caixa4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixas().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caixa1;
    private javax.swing.JButton Caixa2;
    private javax.swing.JButton Caixa3;
    private javax.swing.JButton Caixa4;
    private javax.swing.JButton SenhaComum;
    private javax.swing.JButton SenhaPriori;
    private javax.swing.JButton SenhaRapido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel painelcaixa;
    private javax.swing.JLabel painelsenha;
    private javax.swing.JTextField senhacliente;
    // End of variables declaration//GEN-END:variables
}
